max_width = 120
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable features below
unstable_features = true
style_edition = "2024"
comment_width = 120
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
normalize_doc_attributes = true
wrap_comments = true
